In [2]:
import numpy as np 
import pandas as pd


In [3]:
df = pd.DataFrame({'text':["people watch campusx","campusx watch campusx","people write comment","campusx write comment"],'output':[1,1,0,0]})
df.head()

,text,output
0,people watch campusx,1
1,campusx watch campusx,1
2,people write comment,0
3,campusx write comment,0


In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cnv = CountVectorizer()
bow = cnv.fit_transform(df['text'])


In [5]:
cnv.vocabulary_

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}

In [6]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [7]:
cnv.transform(["campusx has got something comment to write"]).toarray()

array([[1, 1, 0, 0, 1]])

In [8]:
cnv2 = CountVectorizer(ngram_range=(2,2))
bow2 = cnv2.fit_transform(df['text'])

In [11]:
cnv2.vocabulary_

{'people watch': 2,
 'watch campusx': 4,
 'campusx watch': 0,
 'people write': 3,
 'write comment': 5,
 'campusx write': 1}

In [10]:
print(bow2[0].toarray())
print(bow2[1].toarray())
print(bow2[2].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]
[[0 0 0 1 0 1]]


In [ ]:
cnv3 = CountVectorizer(ngram_range=(1,2)) # bag of both unigrams and bigrams
# can do for (1,3) too 

cnv3.fit_transform(df['text'])
cnv3.vocabulary_

{'people': 4,
 'watch': 7,
 'campusx': 0,
 'people watch': 5,
 'watch campusx': 8,
 'campusx watch': 1,
 'write': 9,
 'comment': 3,
 'people write': 6,
 'write comment': 10,
 'campusx write': 2}