In [4]:
import numpy as np 
import pandas as pd

In [6]:
data= pd.read_csv('IMDB Dataset.csv')
data.head()

,review,sentiment
0,One of the other reviewers has mentioned that ...,positive
1,A wonderful little production. <br /><br />The...,positive
2,I thought this was a wonderful way to spend ti...,positive
3,Basically there's a family where a little boy ...,negative
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive


Preprocessing Stage

In [29]:
df = data.iloc[1:1500:]
df.shape

(1499, 2)

In [30]:
df.head()

,review,sentiment
1,A wonderful little production. <br /><br />The...,positive
2,I thought this was a wonderful way to spend ti...,positive
3,Basically there's a family where a little boy ...,negative
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive
5,"Probably my all-time favorite movie, a story o...",positive


Lowercasing

In [31]:
df['review'] = df['review'].str.lower()
df.head()

C:\Users\KIIT0001\AppData\Local\Temp\ipykernel_12264\1300440577.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].str.lower()


,review,sentiment
1,a wonderful little production. <br /><br />the...,positive
2,i thought this was a wonderful way to spend ti...,positive
3,basically there's a family where a little boy ...,negative
4,"petter mattei's ""love in the time of money"" is...",positive
5,"probably my all-time favorite movie, a story o...",positive


Removing HTML Tags

In [32]:
import re

def remove_html_tagsre(text):
    clean = re.compile(r'<.*?>', re.DOTALL)
    return re.sub(clean, '', text)

df['review'] = df['review'].apply(remove_html_tagsre)
df.head()

C:\Users\KIIT0001\AppData\Local\Temp\ipykernel_12264\355156253.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(remove_html_tagsre)


,review,sentiment
1,a wonderful little production. the filming tec...,positive
2,i thought this was a wonderful way to spend ti...,positive
3,basically there's a family where a little boy ...,negative
4,"petter mattei's ""love in the time of money"" is...",positive
5,"probably my all-time favorite movie, a story o...",positive


Removing Punctuation

In [33]:
import string
exclude = string.punctuation
exclude

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [34]:
# def remove_punc(text):
#     word = []
#     for i in text.split():
#         if i in exclude:
#             word.append("")
#         else:
#             word.append(i)

# takes a lot of time so we apply this

def removepunc(text):
    return text.translate(str.maketrans('','',exclude))

In [35]:
df['review'] = df['review'].apply(removepunc)
df.head()

C:\Users\KIIT0001\AppData\Local\Temp\ipykernel_12264\1535469917.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(removepunc)


,review,sentiment
1,a wonderful little production the filming tech...,positive
2,i thought this was a wonderful way to spend ti...,positive
3,basically theres a family where a little boy j...,negative
4,petter matteis love in the time of money is a ...,positive
5,probably my alltime favorite movie a story of ...,positive


Removing Stopwords

In [36]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))
print(list(stop_words)) 

["he's", 'these', 'do', 'wouldn', 'your', 'did', "they've", 'than', 'y', "we're", 'own', 'further', "we've", 'o', "didn't", 'with', "aren't", 'down', 'then', "i've", 'after', 'again', 'when', 'itself', 'ours', 'it', 'were', 'until', 'how', 'not', 'so', 'if', 'their', 'doesn', 'while', 'has', 's', 'here', "shouldn't", 'during', 'wasn', 'who', 'm', 'from', 'his', "don't", 'can', 'or', 'they', "you'll", 'am', 'won', 'be', 'by', 'couldn', 'why', 'the', 'for', "she's", 'ourselves', 'been', 'of', 'he', 'other', 'aren', 're', "they'd", 'are', 'as', 'but', "he'd", 'only', 'is', 'yourself', 'yours', 'mightn', 'any', 'under', "it's", 'just', 'very', "i'd", 'now', 'hadn', 'into', "should've", 't', "we'd", 'was', 'both', 'had', 'those', 'at', "wasn't", 'against', 'hers', "i'm", "you've", 'its', 'up', 'she', 'themselves', 'over', "isn't", "mightn't", 'her', 'our', 'and', 'myself', "they're", "haven't", 'needn', 'me', 'such', 'mustn', 'on', "we'll", 'you', "wouldn't", 'd', "that'll", 'my', "she'll",

In [39]:
# def remove_stopwords(text):
#     new_text = []
#     for word in text.split():
#         if word in stopwords.words('english'):
#             new_text.append("")
#         else:
#             new_text.append(word)
    
#     return " ".join(new_text)

# faster  way
from nltk.corpus import stopwords

# Preload stopwords once
stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    # Split and filter using set membership
    return " ".join(word for word in text.split() if word not in stop_words)


In [40]:
df['review'] = df['review'].astype(str).apply(remove_stopwords)

C:\Users\KIIT0001\AppData\Local\Temp\ipykernel_12264\2045759792.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].astype(str).apply(remove_stopwords)


In [41]:
df.head()

,review,sentiment
1,wonderful little production filming technique ...,positive
2,thought wonderful way spend time hot summer we...,positive
3,basically theres family little boy jake thinks...,negative
4,petter matteis love time money visually stunni...,positive
5,probably alltime favorite movie story selfless...,positive


Find out the number of words in the entire corpus

In [ ]:
words = []
for review in df['review']:
    for word in review.split():
        words.append(word)
len(words)

174560

the total number of unique words(vocabulary) using just python

In [45]:
unique = set(words)
unli = list(unique)
len(unli)

26480

Apply bag words and find the vocabulary also find the times each word has occured

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cnv = CountVectorizer()
bow = cnv.fit_transform(df['review'])
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

bow.toarray().shape

[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]


(1499, 26433)

In [52]:
cnv.vocabulary_

{'wonderful': 26022,
 'little': 13818,
 'production': 18296,
 'filming': 8799,
 'technique': 23298,
 'unassuming': 24486,
 'oldtimebbc': 16457,
 'fashion': 8545,
 'gives': 9877,
 'comforting': 4802,
 'sometimes': 21790,
 'discomforting': 6695,
 'sense': 20769,
 'realism': 18951,
 'entire': 7859,
 'piece': 17566,
 'actors': 603,
 'extremely': 8362,
 'well': 25641,
 'chosen': 4335,
 'michael': 14907,
 'sheen': 21016,
 'got': 10084,
 'polari': 17842,
 'voices': 25291,
 'pat': 17151,
 'truly': 24289,
 'see': 20632,
 'seamless': 20574,
 'editing': 7433,
 'guided': 10355,
 'references': 19129,
 'williams': 25875,
 'diary': 6517,
 'entries': 7875,
 'worth': 26123,
 'watching': 25517,
 'terrificly': 23400,
 'written': 26172,
 'performed': 17364,
 'masterful': 14513,
 'one': 16491,
 'great': 10202,
 'masters': 14525,
 'comedy': 4782,
 'life': 13654,
 'really': 18963,
 'comes': 4796,
 'home': 11233,
 'things': 23574,
 'fantasy': 8508,
 'guard': 10333,
 'rather': 18879,
 'use': 24918,
 'tradition

Apply bag of bi-gram and bag of tri-gram and write down your observation about the dimensionality of the vocabulary

In [61]:
# bi gram
from sklearn.feature_extraction.text import CountVectorizer
cnvbi = CountVectorizer(ngram_range=(2,2)) 
bowbi = cnvbi.fit_transform(df['review'])
bowbi.toarray().shape

(1499, 147253)

In [62]:
cnvbi.vocabulary_

{'wonderful little': 143821,
 'little production': 74261,
 'production filming': 100722,
 'filming technique': 46791,
 'technique unassuming': 127551,
 'unassuming oldtimebbc': 135277,
 'oldtimebbc fashion': 90858,
 'fashion gives': 44116,
 'gives comforting': 53395,
 'comforting sometimes': 24287,
 'sometimes discomforting': 119588,
 'discomforting sense': 33317,
 'sense realism': 113949,
 'realism entire': 103797,
 'entire piece': 39046,
 'piece actors': 96480,
 'actors extremely': 2500,
 'extremely well': 42564,
 'well chosen': 141462,
 'chosen michael': 22027,
 'michael sheen': 81278,
 'sheen got': 115403,
 'got polari': 55222,
 'polari voices': 98374,
 'voices pat': 138758,
 'pat truly': 94344,
 'truly see': 133929,
 'see seamless': 112754,
 'seamless editing': 112063,
 'editing guided': 36586,
 'guided references': 56544,
 'references williams': 105052,
 'williams diary': 142841,
 'diary entries': 32092,
 'entries well': 39122,
 'well worth': 141770,
 'worth watching': 145043,
 '

In [67]:
# tri gram
from sklearn.feature_extraction.text import CountVectorizer
cnvtri = CountVectorizer(ngram_range=(3,3)) 
bowtri = cnvtri.fit_transform(df['review'])
bowtri.toarray().shape

(1499, 169343)

In [68]:
cnvtri.vocabulary_

{'wonderful little production': 165014,
 'little production filming': 84499,
 'production filming technique': 116211,
 'filming technique unassuming': 53140,
 'technique unassuming oldtimebbc': 146227,
 'unassuming oldtimebbc fashion': 155204,
 'oldtimebbc fashion gives': 104773,
 'fashion gives comforting': 49389,
 'gives comforting sometimes': 60653,
 'comforting sometimes discomforting': 27160,
 'sometimes discomforting sense': 137438,
 'discomforting sense realism': 36944,
 'sense realism entire': 131216,
 'realism entire piece': 119600,
 'entire piece actors': 43506,
 'piece actors extremely': 111412,
 'actors extremely well': 2888,
 'extremely well chosen': 47669,
 'well chosen michael': 162230,
 'chosen michael sheen': 24703,
 'michael sheen got': 92770,
 'sheen got polari': 132826,
 'got polari voices': 63011,
 'polari voices pat': 113596,
 'voices pat truly': 158905,
 'pat truly see': 109047,
 'truly see seamless': 153594,
 'see seamless editing': 129767,
 'seamless editing gu

Apply tf-idf and find out the idf scores of words, also find out the vocabulary

In [76]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfi = TfidfVectorizer(ngram_range=(1,3))
tfibow = tfi.fit_transform(df['review']).toarray()

print(tfibow.shape)


(1499, 343029)


In [77]:
tfibow

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [78]:
tfi.vocabulary_

{'wonderful': 334764,
 'little': 172071,
 'production': 235177,
 'filming': 108694,
 'technique': 297051,
 'unassuming': 314967,
 'oldtimebbc': 212088,
 'fashion': 102038,
 'gives': 123893,
 'comforting': 56247,
 'sometimes': 278796,
 'discomforting': 76954,
 'sense': 265792,
 'realism': 242340,
 'entire': 90322,
 'piece': 225456,
 'actors': 5858,
 'extremely': 98464,
 'well': 329218,
 'chosen': 51059,
 'michael': 188869,
 'sheen': 269243,
 'got': 128084,
 'polari': 229812,
 'voices': 322944,
 'pat': 220531,
 'truly': 311665,
 'see': 262247,
 'seamless': 261500,
 'editing': 84765,
 'guided': 131445,
 'references': 245334,
 'williams': 332640,
 'diary': 74135,
 'entries': 90585,
 'worth': 337395,
 'watching': 326822,
 'terrificly': 298581,
 'written': 339469,
 'performed': 223373,
 'masterful': 184420,
 'one': 212245,
 'great': 129283,
 'masters': 184548,
 'comedy': 55562,
 'life': 167775,
 'really': 242756,
 'comes': 55934,
 'home': 140533,
 'things': 301037,
 'fantasy': 101547,
 'guar

In [72]:
print(tfi.idf_)
print(tfi.get_feature_names_out())

[7.62007321 7.62007321 7.62007321 ... 7.62007321 7.62007321 7.62007321]
['007' '007 debut' '007 debut goldeneyethis' ... 'ísnt'
 'ísnt entertaining' 'ísnt entertaining wanna']


In [79]:
np.count_nonzero(tfibow[0])

242

In [80]:
feature_names = tfi.get_feature_names_out()
row = tfibow[0]

nonzero_idx = row.nonzero()[0]
for i in nonzero_idx[:10]:
    print(feature_names[i], row[i])

actors 0.02705571845986676
actors extremely 0.0698413172197721
actors extremely well 0.0698413172197721
chosen 0.05977205314909973
chosen michael 0.0698413172197721
chosen michael sheen 0.0698413172197721
comedy 0.031303462912696284
comedy life 0.0698413172197721
comedy life realism 0.0698413172197721
comes 0.03123531806985882
