In [ ]:
import numpy as np
a1 = np.arange(10)
a2 = np.arange(16,dtype = int).reshape((4,4))
a3 = np.arange(18).reshape((2,3,3))
# print(a1)
# print(a2)
# print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [ ]:
# ndim = gives us the dimension of the numpy array
a1.ndim
a2.ndim
a3.ndim

3

In [ ]:
# gives us the shape array
a1.shape
a2.shape
a3.shape

(2, 3, 3)

In [ ]:
# size : gives us the total number of elements
print(a3.size)

18


In [10]:
# itemsize: gives us the space taken by a datatype

# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
int64
int64


In [11]:
# changing datatype
a3.astype(np.int32)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]], dtype=int32)