In [4]:
import numpy as np
a1 = np.random.random((3,4))
a1

array([[0.13825696, 0.871986  , 0.10855528, 0.49003836],
       [0.14845184, 0.19228354, 0.22556863, 0.96663532],
       [0.91293282, 0.62248707, 0.15643089, 0.73731703]])

In [7]:
print(np.sum(a1))
print(np.max(a1))
print(np.min(a1))
print(np.prod(a1))

5.570943771280711
0.9666353245198397
0.10855528424321903
2.616330395165996e-06


In [ ]:
# har row ka ops
import numpy as np
a1 = np.random.random((3,4))
a1  = np.round(a1*100)
print(a1)
# 0-> col ans 1->row
np.max(a1 , axis = 0)
np.min(a1,axis = 1)

# har col ya row ka prod
np.sum(a1,axis=0)
np.prod(a1,axis=1)


[[ 8. 16. 55. 81.]
 [15. 22. 15. 73.]
 [34. 75. 21. 60.]]


array([ 570240.,  361350., 3213000.])

In [ ]:
# statistical ops
import numpy as np
a1 = np.random.random((3,4))
a1  = np.round(a1*100)
print(a1)
np.mean(a1)
np.mean(a1,axis=0)

np.median(a1)
np.var(a1) #variance
np.std(a1) #standard deviation

[[ 41.  24.  64. 100.]
 [  9.  10.  41.  99.]
 [  1.  89.  62.  56.]]


array([17.        , 41.        , 55.66666667, 85.        ])

In [18]:
import numpy as np
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12).reshape(4,3)
print(a1)
print(a2)
np.dot(a1,a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [20]:
# log and exponents
np.log(a1)
np.exp(a1)

C:\Users\KIIT0001\AppData\Local\Temp\ipykernel_23248\1488485187.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [ ]:
import numpy as np
a1 = np.random.random((3,4))
a1  = np.round(a1*100)
print(a1)

# can do round/floor/ceil