In [3]:
import numpy as np
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# scalar operations
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a1 = a1**2 # scalar ops
a1 = a1 > 8 # relational ops
print(a1)

[[False False False False]
 [False False False False]
 [False  True  True  True]]


In [ ]:
# vector OPs (two arrays of same shape can be operated together)
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [6]:
import numpy as np
a2 = np.arange(12,24).reshape(3,4)
np.transpose(a2)
a2.T

array([[12, 16, 20],
       [13, 17, 21],
       [14, 18, 22],
       [15, 19, 23]])

In [9]:
a3 = np.arange(12,24).reshape(2,2,3)
print(a3)
np.ravel(a3)

[[[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [13]:
# stacking & splitting

# Horizontal stacking
a1 = np.arange(12).reshape(3,4)
a2  = np.arange(12,24).reshape(3,4)
np.hstack((a1,a2))
np.vstack((a1,a2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [17]:
# Splitting
a1 = np.arange(16).reshape(4,4)
a2  = np.arange(12,28).reshape(4,4)
print(np.hsplit(a1,2))
print(np.vsplit(a2,2))


[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[array([[12, 13, 14, 15],
       [16, 17, 18, 19]]), array([[20, 21, 22, 23],
       [24, 25, 26, 27]])]
