In [3]:
import numpy as np
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)


[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [8]:
# indexing
print(a1[-1])
print(a2[0][2])
print(a3[1][1][1])

9
2
7


In [12]:
a1
print(a1[2:6:1])

[2 3 4 5]


In [14]:
print(a2)
print(a2[0,:])
print(a2[:,2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[ 2  6 10]


In [59]:
print(a2)
# print(a2[0:2,0:])
print(a2[::2,::3 ])
# print(a2[::2,1::2])
# print(a2[1:2:,::3])
print(a2[0:2:1,1::1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  3]
 [ 8 11]]
[[1 2 3]
 [5 6 7]]


In [65]:
a3 = np.arange(27).reshape(3,3,3)
# print(a3)
# print(a3[2,1::,1::])
print(a3[0::2,0:1:2,::2])

[[[ 0  2]]

 [[18 20]]]


In [68]:
for i in a2:
    print(i)
for i in a3:
    print(i)
for i in a1:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]
0
1
2
3
4
5
6
7
8
9


In [70]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
