In [4]:
import numpy as np
a = np.array([1,2,3,5,6])
print(a)
print(type(a))

[1 2 3 5 6]
<class 'numpy.ndarray'>


In [9]:
import numpy as np 
d2 = np.array([[12,3,4,5],[1,2,3,4]])
print(d2)


[[12  3  4  5]
 [ 1  2  3  4]]


In [ ]:
# 3d array (tensors)
import numpy as np 
d3 = np.array([[[1,2],[1,2]],[[4,5],[6,8]]])
print(d3)

[[[1 2]
  [1 2]]

 [[4 5]
  [6 8]]]


In [14]:
# dtype (pasand ke datatype a numpy array)

np.array([12,3,4,5],dtype = float)
np.array([12,3,4,5],dtype = bool)
np.array([12,3,4,5],dtype = complex)


array([12.+0.j,  3.+0.j,  4.+0.j,  5.+0.j])

In [21]:
# np.arrange(inclusive , exclusive)
np.arange(1,11)
np.arange(1,13).reshape(3,4)
np.arange(1,13).reshape(2,3,2)
# reshape ka multiply equals to the arrange multiply
 

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [26]:
np.ones((3,4))
np.zeros((4,5))
np.random.random((2,3))

array([[0.67121179, 0.15140108, 0.91690548],
       [0.30017652, 0.81583327, 0.1155946 ]])

In [ ]:
#  np.linspace (linear space) (equal distance points are generated)
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [30]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])