In [7]:
import numpy as np
a1 = np.random.randint(1,100,15)
a1 = np.sort(a1)
print(a1)



[ 5  6 11 20 29 32 35 38 46 57 71 78 85 94 96]


In [16]:
# 2-d array

a2 = np.random.randint(1,100,15).reshape(3,5)
print(a2)
print("\n")
b = np.sort(a2,axis=1)
print(b)

[[42 90 83 90 11]
 [18 89  3 49 69]
 [56 95 19 69 34]]


[[11 42 83 90 90]
 [ 3 18 49 69 89]
 [19 34 56 69 95]]


In [19]:
# np.append

# np.concatenate
c = np.random.randint(1,100,15).reshape(3,5)
d = np.random.randint(1,100,15).reshape(3,5)
print(np.concatenate((c,d),axis=0))

[[46 86 76 64 46]
 [ 4  6 17 98 55]
 [67  4 15 28 27]
 [69 13 71  9 19]
 [84 83 29 77 74]
 [95  9 57 78 46]]


In [21]:
a = np.array([1,1,1,2,3,4,5,3,4,5,5])
print(a)

print(np.unique(a))

[1 1 1 2 3 4 5 3 4 5 5]
[1 2 3 4 5]


In [27]:
a1 = np.random.randint(1,50,10)
print(a1)
print(a1.shape)
print(np.expand_dims(a1,axis=0).shape)


[ 4 49 22 31 26 16 21  6 10  7]
(10,)
(1, 10)


In [32]:
a1 = np.random.randint(1,100,10)
print(a1)
print(a1[a1>50])
print(np.where(a1>50))

[89 77 63 23 86 36 39 37 51 44]
[89 77 63 86 51]
(array([0, 1, 2, 4, 8]),)


In [35]:
# can change array with condition

# np.where(condn,true,false)
print(np.where(a1>50,0,a1))
print(np.where(a1>50,a1,0))

[ 0  0  0 23  0 36 39 37  0 44]
[89 77 63  0 86  0  0  0 51  0]


In [ ]:
# argmax :- greatest element at which position
# argmin :- smallest element at which position
np.argmax(a1)

d = np.random.randint(1,100,15).reshape(3,5)
print(d)
np.argmax(d)

[[31  7 38 75 63]
 [31 87 74 77 49]
 [44 85 68 21 87]]


np.int64(6)

In [43]:
# cumsum 
# cumprod
print(a1)
# print(np.cumsum(a1))
# print(np.cumprod(a1))

d = np.random.randint(1,100,15).reshape(3,5)
print(d)
print(np.cumsum(d,axis=1))


[89 77 63 23 86 36 39 37 51 44]
[[30  7 98 23 90]
 [95 11 65 99 77]
 [69 74 42  7 77]]
[[ 30  37 135 158 248]
 [ 95 106 171 270 347]
 [ 69 143 185 192 269]]


In [45]:
# for histrogram
print(a1)
np.histogram(a1,(10,20,30,40,50,60,70,80,90))

[89 77 63 23 86 36 39 37 51 44]


(array([0, 1, 3, 1, 1, 1, 1, 2]), array([10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [ ]:
# for pearson - corelation
print(a1)
salary = np.array([20000,30000,40000,50000,60000])
# exp = np.array([1,2,3,4,5]) +ve corelation
# exp = np.array([5,4,3,2,1]) -ve corelation
exp = np.array([8,3,5,1,5])

print(np.corrcoef(salary,exp))

[89 77 63 23 86 36 39 37 51 44]
[[ 1.         -0.48507125]
 [-0.48507125  1.        ]]


In [ ]:
# isin - tells us that multiple elements are present in  an array of not
b = np.array([10,2,23,86,37])
print(np.isin(b,a1))


[False False  True  True  True]


In [52]:
# flip- mirror image of the object keeping the shape intact
c = np.arange(1,10)
print(c)
print(np.flip(c))

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


In [ ]:
c = np.arange(1,11).reshape(2,5)
print(c)
print(np.flip(c,axis=0)) #row-wise
print(np.flip(c)) # both columnwise and rowwise

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 6  7  8  9 10]
 [ 1  2  3  4  5]]
[[10  9  8  7  6]
 [ 5  4  3  2  1]]
